swagger: "2.0"
info:
  title: "PlatHome"
  version: "0.0.1"
  description: "Home Netework Watcher Service"
  contact:
    name: "reud"
    url: "https://reud.net/"
    email: "mail@reud.net"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
consumes:
  - "application/json"
produces:
  - "application/json"
host: "0.0.0.0:8080"
paths:
  /device:
    put:
      parameters:
        - name: "device"
          in: "body"
          required: true
          description: "put to DB a new Device"
          schema:
            $ref: '#/definitions/Device'
      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
    delete:
      summary: "Delete Devices from DB by IP(converted)"
      parameters:
        - name: "ip"
          in: "query"
          required: true
          description: "delete Device"
          type: "string"


      responses:
        200:
          description: "delete successful"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        404:
          description: "device not found"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
    get:
      summary: "get All Device  from DB"
      responses:
        200:
          description: "get successful"
          schema:
            type: "array"
            items:
              $ref: '#/definitions/Device'
  /ping:
    get:
      summary: "PING by P(converted)"
      parameters:
        - name: "ip"
          in: "query"
          required: true
          description: "device ip"
          type: "string"


      responses:
        200:
          description: "pink finished"
          schema:
            type: "object"
            properties:
              result:
                type: "string"
        404:
          description: "record not found"
          schema:
            type: "object"
            properties:
              result:
                type: "string"
        500:
          description: "Internal Server Error"
          schema:
            type: "object"
            properties:
              result:
                type: "string"

definitions:
  Device:
    type: "object"
    required:
      - type
      - ip
      - hostname
      - description
      - ezRequesterModels
      - state
    properties:
      type:
        type: "string"
      ip:
        type: "string"
      hostname:
        type: "string"
      description:
        type: "string"
      ezRequesterModels:
        type: "array"
        items:
          $ref: '#/definitions/EzRequesterModel'
      state:
        type: "string"
  EzRequesterModel:
    type: "object"
    required:
      - protocol
      - parameter
    properties:
      protocol:
        type: "string"
      parameter:
        type: "string"


